version: 2
updates:
  - package-ecosystem: "gradle"  # CORRECTED: Must be set to the right ecosystem
    directory: "/"           # CORRECT: Looks in the root directory
    schedule:
      interval: "weekly"
